[[colors.indexed_colors]]
color = "0xF8BD96"
index = 16

[[colors.indexed_colors]]
color = "0xF5E0DC"
index = 17

[colors.bright]
black = "0x988BA2"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

[colors.normal]
black = "0x6E6C7E"
blue = "0x96CDFB"
cyan = "0x89DCEB"
green = "0xABE9B3"
magenta = "0xF5C2E7"
red = "0xF28FAD"
white = "0xD9E0EE"
yellow = "0xFAE3B0"

[colors.primary]
background = "0x151520"
foreground = "0xc9E0EE"

[font]
size = 10.0

[font.bold]
family = "Comic Code Ligatures"
style = "Bold"

[font.bold_italic]
family = "Monaspace Argon Medium"
style = "Italic"

# [font.cursor]
# cursor = "#ffa0ff"
# text = "CellBackground"

[font.italic]
family = "Monaspace Radon"
style = "Italic"

[font.normal]
family = "Monaspace Argon Medium"
style = "Regular"

[font.offset]
x = 0
y = 2

[mouse]
hide_when_typing = false

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 11

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 190
lines = 50

[window.padding]
x = 0
y = 0
